name: Sentry Release

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Create Sentry release
      uses: getsentry/action-release@v1.0.0
      env:
        SENTRY_AUTH_TOKEN: ${{ `a9e824e28d3749c1a50124f71d0f350ff8f2131d9fcf4db095101634ac4ab94e` }}
        SENTRY_ORG: ${{ `bitcs-j7` }}
        SENTRY_PROJECT: ${{ `4503988823130112` }}
      with:
        environment: production
